"""
Frappe Email Module

Complete email infrastructure for the Frappe framework replacement:
- Email queue with retry logic and status tracking
- sendmail() API compatible with the original Frappe signature
- SMTP backend abstraction
- Communication logging (every email is a Communication document)
- Contact list / autocomplete helpers
- System manager notification helpers
- Unsubscribe link generation

The module uses ``EmailQueue`` as the core queueing mechanism and
``SMTPConnection`` for actual SMTP delivery.  Both are thin layers
that can be swapped out for external providers (SendGrid, SES, …)
via hooks.

Typical flow::

    # From application code
    frappe.sendmail(
        recipients=["user@example.com"],
        subject="Welcome",
        message="<h1>Hello!</h1>",
        reference_doctype="Sales Order",
        reference_name="SO-00001",
    )

    # Background worker picks up queue and delivers
    from frappe.email import flush
    flush()
"""

from __future__ import annotations

import hashlib
import json
import logging
import os
import secrets
import time
from collections.abc import Sequence
from datetime import datetime, timedelta
from typing import Any, Optional, Union

import frappe
from frappe.exceptions import OutgoingEmailError, ValidationError
from frappe.types import _dict
from frappe.utils import (
    cint,
    cstr,
    get_url,
    now,
    now_datetime,
    split_emails,
    strip_html,
    validate_email_address,
)
from frappe.utils.background_jobs import enqueue
from frappe.website.serve import render_string

logger = logging.getLogger("frappe.email")

# ─── Module-level exports ───────────────────────────────────────────────────

__all__ = [
    "sendmail",
    "sendmail_to_system_managers",
    "get_system_managers",
    "get_contact_list",
    "get_communication_doctype",
    "make_communication",
    "flush",
    "get_email_queue",
    "get_unsubscribe_message",
    "get_unsubscribed_users",
]


# ═══════════════════════════════════════════════════════════════════════════════
#  PUBLIC API — sendmail
# ═══════════════════════════════════════════════════════════════════════════════


def sendmail(
    recipients: Optional[Union[str, list[str]]] = None,
    sender: Optional[str] = None,
    subject: Optional[str] = None,
    message: Optional[str] = None,
    reference_doctype: Optional[str] = None,
    reference_name: Optional[str] = None,
    add_unsubscribe_link: int = 1,
    attachments: Optional[list[dict]] = None,
    reply_to: Optional[str] = None,
    cc: Optional[Union[str, list[str]]] = None,
    bcc: Optional[Union[str, list[str]]] = None,
    print_format: Optional[str] = None,
    send_email: int = 1,
    now: bool = False,
    communication: Optional[str] = None,
    read_receipt: bool = False,
    is_notification: bool = False,
    print_letterhead: bool = True,
    email_template: Optional[str] = None,
    **kwargs: Any,
) -> "EmailQueue":
    """Send an email.

    If *send_email* is 1 (default) the message is added to the email queue
    and will be delivered by a background worker.  If *now* is ``True`` the
    email is sent synchronously in the current process.

    Every outgoing message is also stored as a *Communication* document so
    that the full correspondence history is available from any document.

    Parameters
    ----------
    recipients :
        Primary recipient(s).  String is split on commas.
    sender :
        From address.  Falls back to ``config.mail_login`` or
        ``config.auto_email_id``.
    subject :
        Email subject line.
    message :
        HTML body.  Plain text is auto-generated by stripping HTML.
    reference_doctype / reference_name :
        Link the email to a document for communication history.
    add_unsubscribe_link :
        Append an unsubscribe footer when >0.
    attachments :
        List of ``{"fname": str, "fcontent": bytes}`` dicts.
    reply_to :
        Reply-To header address.
    cc / bcc :
        Carbon-copy / blind carbon-copy addresses.
    print_format :
        Name of a print format to render as PDF attachment.
    send_email :
        0 = create Communication only, do not queue for delivery.
    now :
        Bypass the queue and deliver immediately (synchronous).
    communication :
        Name of an existing Communication document to reuse.
    read_receipt :
        Request a read-receipt (Disposition-Notification-To).
    is_notification :
        Mark the Communication as an automated notification.
    print_letterhead :
        Include the company letterhead when rendering a print format.
    email_template :
        Name of an *Email Template* document to load subject/body from.

    Returns
    -------
    EmailQueue :
        The queue record created for this message.
    """
    if frappe.are_emails_muted():
        logger.info("Emails are muted; skipping sendmail")
        return None  # type: ignore[return-value]

    # ── Resolve recipients ──
    recipient_list = _normalize_address_list(recipients)
    cc_list = _normalize_address_list(cc)
    bcc_list = _normalize_address_list(bcc)

    if not recipient_list and not cc_list and not bcc_list:
        logger.warning("sendmail called with no recipients")
        return None  # type: ignore[return-value]

    # ── Resolve sender ──
    sender = sender or _get_default_sender()

    # ── Load email template if specified ──
    if email_template and not (subject and message):
        subject, message = _load_email_template(email_template, kwargs)

    subject = cstr(subject)
    message = cstr(message)

    # ── Render print format as attachment ──
    if print_format and reference_doctype and reference_name:
        from frappe.printing import get_pdf

        try:
            pdf_data = get_pdf(
                reference_doctype,
                reference_name,
                print_format=print_format,
                letterhead=print_letterhead,
            )
            if pdf_data:
                attachments = attachments or []
                attachments.append(
                    {
                        "fname": f"{reference_name}.pdf",
                        "fcontent": pdf_data,
                    }
                )
        except Exception:
            logger.exception("Failed to generate PDF attachment")

    # ── Create / update Communication ──
    if not communication:
        comm = make_communication(
            doctype=reference_doctype,
            name=reference_name,
            subject=subject,
            content=message,
            sender=sender,
            recipients=", ".join(recipient_list),
            cc=", ".join(cc_list) if cc_list else None,
            bcc=", ".join(bcc_list) if bcc_list else None,
            communication_medium="Email",
            sent_or_received="Sent",
            send_email=bool(send_email),
            read_receipt=read_receipt,
            email_template=email_template,
        )
        communication = comm.name
    else:
        comm = frappe.get_doc("Communication", communication)

    # ── Build unsubscribe link ──
    unsubscribe_msg = ""
    if add_unsubscribe_link and reference_doctype and reference_name:
        unsubscribe_msg = get_unsubscribe_message(reference_doctype, reference_name)
        if unsubscribe_msg and message:
            message = message + "<br><br>" + unsubscribe_msg

    # ── Queue or send immediately ──
    if not send_email:
        return None  # type: ignore[return-value]

    queue_doc = EmailQueue(
        recipients=recipient_list,
        cc=cc_list,
        bcc=bcc_list,
        sender=sender,
        subject=subject,
        message=message,
        attachments=attachments or [],
        reply_to=reply_to,
        reference_doctype=reference_doctype,
        reference_name=reference_name,
        communication=communication,
        read_receipt=read_receipt,
        is_notification=is_notification,
    )

    if now:
        queue_doc.send()
    else:
        queue_doc.add_to_queue()

    return queue_doc


def sendmail_to_system_managers(subject: str, message: str, **kwargs: Any) -> None:
    """Send an email to every user with the *System Manager* role."""
    managers = get_system_managers()
    if not managers:
        logger.warning("No System Managers found; cannot send notification")
        return

    sendmail(
        recipients=managers,
        subject=subject,
        message=message,
        **kwargs,
    )


# ═══════════════════════════════════════════════════════════════════════════════
#  COMMUNICATION DOCUMENTS
# ═══════════════════════════════════════════════════════════════════════════════


def make(
    doctype: Optional[str] = None,
    name: Optional[str] = None,
    content: Optional[str] = None,
    subject: Optional[str] = None,
    sent_or_received: str = "Sent",
    sender: Optional[str] = None,
    sender_full_name: Optional[str] = None,
    recipients: Optional[Union[str, list[str]]] = None,
    cc: Optional[str] = None,
    bcc: Optional[str] = None,
    communication_medium: str = "Email",
    send_email: bool = False,
    print_html: Optional[str] = None,
    print_format: Optional[str] = None,
    attachments: Optional[list[dict]] = None,
    ignore_doctype_permissions: bool = False,
    read_receipt: bool = False,
    email_template: Optional[str] = None,
    **kwargs: Any,
) -> "Document":
    """Create a *Communication* document.

    This is the canonical way to log an email (or other communication) in
    Frappe.  The Communication is linked to a reference document so that
    the full correspondence history can be shown on any form.
    """
    return make_communication(
        doctype=doctype,
        name=name,
        content=content,
        subject=subject,
        sent_or_received=sent_or_received,
        sender=sender,
        sender_full_name=sender_full_name,
        recipients=recipients,
        cc=cc,
        bcc=bcc,
        communication_medium=communication_medium,
        send_email=send_email,
        print_html=print_html,
        print_format=print_format,
        attachments=attachments,
        ignore_doctype_permissions=ignore_doctype_permissions,
        read_receipt=read_receipt,
        email_template=email_template,
        **kwargs,
    )


def make_communication(
    doctype: Optional[str] = None,
    name: Optional[str] = None,
    content: Optional[str] = None,
    subject: Optional[str] = None,
    sent_or_received: str = "Sent",
    sender: Optional[str] = None,
    sender_full_name: Optional[str] = None,
    recipients: Optional[Union[str, list[str]]] = None,
    cc: Optional[str] = None,
    bcc: Optional[str] = None,
    communication_medium: str = "Email",
    send_email: bool = False,
    print_html: Optional[str] = None,
    print_format: Optional[str] = None,
    attachments: Optional[list[dict]] = None,
    ignore_doctype_permissions: bool = False,
    read_receipt: bool = False,
    email_template: Optional[str] = None,
    **kwargs: Any,
) -> "Document":
    """Create a *Communication* document (low-level, internal)."""
    # Normalize recipients to a comma-separated string
    if isinstance(recipients, (list, tuple)):
        recipients = ", ".join(recipients)

    # Resolve sender info
    if not sender:
        sender = _get_default_sender()
    if not sender_full_name:
        try:
            sender_full_name = frappe.utils.get_fullname(
                frappe.session.user if hasattr(frappe.session, "user") else "Administrator"
            )
        except Exception:
            sender_full_name = sender

    data = {
        "doctype": "Communication",
        "subject": subject or "",
        "content": content or "",
        "communication_type": "Communication",
        "communication_medium": communication_medium,
        "sent_or_received": sent_or_received,
        "sender": sender,
        "sender_full_name": sender_full_name,
        "recipients": recipients or "",
        "cc": cc or "",
        "bcc": bcc or "",
        "reference_doctype": doctype,
        "reference_name": name,
        "read_receipt": cint(read_receipt),
        "email_template": email_template,
        "delivery_status": "",
    }

    # Add any extra kwargs that match Communication fields
    for key, value in kwargs.items():
        if key not in data:
            data[key] = value

    doc = frappe.get_doc(data)
    doc.flags.ignore_permissions = ignore_doctype_permissions
    doc.insert(ignore_permissions=ignore_doctype_permissions)

    # Attach files
    if attachments:
        for att in attachments:
            if isinstance(att, dict) and "fname" in att and "fcontent" in att:
                _add_attachment_to_communication(doc, att["fname"], att["fcontent"])

    return doc


# ═══════════════════════════════════════════════════════════════════════════════
#  CONTACT HELPERS
# ═══════════════════════════════════════════════════════════════════════════════


def get_system_managers() -> list[str]:
    """Return a list of email addresses for users with the *System Manager* role.

    Uses the ``Has Role`` and ``User`` DocTypes.  Falls back to the
    ``auto_email_id`` configured for the site if no managers are found.
    """
    try:
        managers = frappe.db.sql(
            """
            SELECT DISTINCT u.email
            FROM `tabUser` u
            INNER JOIN `tabHas Role` hr ON hr.parent = u.name
            WHERE hr.role = 'System Manager'
                AND u.enabled = 1
                AND u.email IS NOT NULL
                AND u.email != ''
            ORDER BY u.email
            """,
            as_dict=False,
        )
        emails = [row[0] for row in managers if row[0] and validate_email_address(row[0])]
        if emails:
            return emails
    except Exception:
        logger.debug("get_system_managers query failed", exc_info=True)

    # Fallback: auto_email_id from config
    auto_email = frappe.conf.get("auto_email_id")
    if auto_email:
        return [auto_email]

    return []


def get_contact_list(doctype: str, fieldname: str, txt: str) -> list[_dict]:
    """Return matching contacts for autocomplete widgets.

    Searches *Contact* documents by first name, last name, or email and
    returns up to 20 matches.
    """
    txt = cstr(txt).strip()
    if not txt:
        return []

    search_pattern = f"%{txt}%"

    try:
        contacts = frappe.db.sql(
            """
            SELECT DISTINCT email_id AS value, full_name AS label
            FROM `tabContact`
            WHERE (
                first_name LIKE %s
                OR last_name LIKE %s
                OR email_id LIKE %s
            )
            AND email_id IS NOT NULL
            AND email_id != ''
            ORDER BY full_name
            LIMIT 20
            """,
            (search_pattern, search_pattern, search_pattern),
            as_dict=True,
        )
        return [_dict(c) for c in contacts if c.get("value")]
    except Exception:
        logger.debug("get_contact_list query failed", exc_info=True)
        return []


def get_communication_doctype(
    doctype: str,
    docname: str,
    limit: int = 50,
) -> list[dict]:
    """Return *Communication* records linked to a document.

    These are shown in the *Communication* timeline on every form.
    """
    try:
        comms = frappe.db.get_all(
            "Communication",
            filters={
                "reference_doctype": doctype,
                "reference_name": docname,
            },
            fields=[
                "name",
                "subject",
                "content",
                "sender",
                "sender_full_name",
                "recipients",
                "cc",
                "communication_medium",
                "sent_or_received",
                "creation",
                "modified",
                "read_receipt",
                "delivery_status",
                "communication_type",
            ],
            order_by="creation desc",
            limit_page_length=limit,
        )
        return comms
    except Exception:
        logger.debug("get_communication_doctype query failed", exc_info=True)
        return []


# ═══════════════════════════════════════════════════════════════════════════════
#  UNSUBSCRIBE HELPERS
# ═══════════════════════════════════════════════════════════════════════════════


def get_unsubscribe_message(doctype: str, docname: str) -> str:
    """Return an HTML unsubscribe footer for bulk emails.

    The footer contains a link back to the site with a signed token so
    that the unsubscribe view can verify the request.
    """
    try:
        token = _generate_unsubscribe_token(doctype, docname)
        unsubscribe_url = f"{get_url()}/api/method/frappe.email.unsubscribe?" f"doctype={doctype}&name={docname}&token={token}"

        return (
            '<div style="margin-top: 20px; padding-top: 10px; '
            'border-top: 1px solid #ddd; font-size: 12px; color: #888;">'
            f'<a href="{unsubscribe_url}">Unsubscribe from this list</a>'
            "</div>"
        )
    except Exception:
        return ""


def get_unsubscribed_users(doctype: str, docname: str) -> list[str]:
    """Return the list of email addresses that have unsubscribed from
    notifications for the given document."""
    try:
        return frappe.db.get_all(
            "Email Unsubscribe",
            filters={
                "reference_doctype": doctype,
                "reference_name": docname,
            },
            pluck="email",
        ) or []
    except Exception:
        return []


# ═══════════════════════════════════════════════════════════════════════════════
#  QUEUE FLUSHING (called by background worker)
# ═══════════════════════════════════════════════════════════════════════════════


def flush() -> dict[str, int]:
    """Deliver all pending emails in the queue.

    This function is invoked by the background job scheduler.  It fetches
    all *Email Queue* documents with status *Not Sent* and attempts to
    deliver them, retrying failed items up to ``config.max_email_retry``
    times (default 3).

    Returns
    -------
    dict :
        ``{"sent": int, "failed": int, "pending": int}``
    """
    max_retries = cint(frappe.conf.get("max_email_retry", 3))
    retry_interval = cint(frappe.conf.get("email_retry_interval", 300))  # 5 min

    pending = _get_pending_queue_items(max_retries, retry_interval)

    stats = {"sent": 0, "failed": 0, "pending": 0}

    for queue_item in pending:
        try:
            queue_item.send()
            stats["sent"] += 1
        except Exception as exc:
            logger.warning(
                "Failed to send email queue %s: %s", queue_item.name, exc,
                exc_info=True,
            )
            queue_item.mark_failed(str(exc))
            stats["failed"] += 1

    stats["pending"] = len(pending) - stats["sent"] - stats["failed"]
    return stats


# ═══════════════════════════════════════════════════════════════════════════════
#  EMAIL QUEUE  (internal data class)
# ═══════════════════════════════════════════════════════════════════════════════


class EmailQueue:
    """Represents a single email in the queue.

    This class wraps the *Email Queue* DocType and provides a Pythonic
    interface for creating, persisting, and sending queued messages.
    """

    def __init__(
        self,
        recipients: list[str],
        sender: str,
        subject: str,
        message: str,
        cc: Optional[list[str]] = None,
        bcc: Optional[list[str]] = None,
        attachments: Optional[list[dict]] = None,
        reply_to: Optional[str] = None,
        reference_doctype: Optional[str] = None,
        reference_name: Optional[str] = None,
        communication: Optional[str] = None,
        read_receipt: bool = False,
        is_notification: bool = False,
    ):
        self.name: Optional[str] = None
        self.recipients = recipients
        self.cc = cc or []
        self.bcc = bcc or []
        self.sender = sender
        self.subject = subject
        self.message = message
        self.attachments = attachments or []
        self.reply_to = reply_to
        self.reference_doctype = reference_doctype
        self.reference_name = reference_name
        self.communication = communication
        self.read_receipt = read_receipt
        self.is_notification = is_notification
        self.status = "Not Sent"
        self.retry = 0
        self.error = None

    # ── Persistence ──

    def add_to_queue(self) -> None:
        """Create an *Email Queue* document in the database."""
        try:
            doc = frappe.get_doc(
                {
                    "doctype": "Email Queue",
                    "sender": self.sender,
                    "recipients": json.dumps(self.recipients),
                    "cc": json.dumps(self.cc),
                    "bcc": json.dumps(self.bcc),
                    "subject": self.subject,
                    "message": self.message,
                    "reference_doctype": self.reference_doctype,
                    "reference_name": self.reference_name,
                    "communication": self.communication,
                    "status": "Not Sent",
                    "retry": 0,
                    "read_receipt": cint(self.read_receipt),
                    "is_notification": cint(self.is_notification),
                }
            )
            doc.insert(ignore_permissions=True)
            self.name = doc.name

            # Store attachment metadata on the queue doc
            if self.attachments:
                for att in self.attachments:
                    att_doc = frappe.get_doc(
                        {
                            "doctype": "Email Queue Recipient",
                            "parent": doc.name,
                            "parenttype": "Email Queue",
                            "parentfield": "recipients_list",
                            "recipient": att.get("fname", ""),
                            "status": " attachment",
                        }
                    )
                    att_doc.insert(ignore_permissions=True)
        except Exception:
            logger.exception("Failed to add email to queue")

    def send(self) -> None:
        """Deliver the email via SMTP immediately."""
        from frappe.email.smtp import SMTPConnection

        conn = SMTPConnection()

        conn.send_message(
            sender=self.sender,
            recipients=self.recipients,
            subject=self.subject,
            message=self.message,
            cc=self.cc,
            bcc=self.bcc,
            attachments=self.attachments,
            reply_to=self.reply_to,
            read_receipt=self.read_receipt,
        )

        self.status = "Sent"
        self._update_status()

        # Update linked Communication
        if self.communication:
            self._update_communication_status("Delivered")

    def mark_failed(self, error: str) -> None:
        """Mark the queue item as failed and increment retry count."""
        self.retry += 1
        self.error = error
        self.status = "Error"
        self._update_status()

        if self.communication:
            self._update_communication_status("Error")

    def _update_status(self) -> None:
        """Persist status changes back to the database."""
        if self.name:
            try:
                frappe.db.set_value(
                    "Email Queue",
                    self.name,
                    {"status": self.status, "retry": self.retry, "error": self.error},
                )
            except Exception:
                logger.debug("Failed to update queue status for %s", self.name)

    def _update_communication_status(self, delivery_status: str) -> None:
        """Update the linked Communication document delivery status."""
        if self.communication:
            try:
                frappe.db.set_value(
                    "Communication",
                    self.communication,
                    "delivery_status",
                    delivery_status,
                )
            except Exception:
                logger.debug(
                    "Failed to update communication status for %s",
                    self.communication,
                )


# ═══════════════════════════════════════════════════════════════════════════════
#  INTERNAL HELPERS
# ═══════════════════════════════════════════════════════════════════════════════


def _normalize_address_list(value: Optional[Union[str, list[str], tuple[str]]]) -> list[str]:
    """Convert a recipient argument into a clean list of email addresses."""
    if not value:
        return []
    if isinstance(value, str):
        return [a.strip() for a in value.split(",") if a.strip()]
    return [a.strip() for a in value if a and isinstance(a, str) and a.strip()]


def _get_default_sender() -> str:
    """Return the default outgoing email address for this site."""
    sender = frappe.conf.get("mail_login") or frappe.conf.get("auto_email_id")
    if not sender:
        try:
            sender = frappe.session.user if hasattr(frappe.session, "user") else "admin@example.com"
        except Exception:
            sender = "admin@example.com"
    return sender


def _load_email_template(
    template_name: str, context: dict[str, Any]
) -> tuple[str, str]:
    """Load subject and body from an *Email Template* document."""
    try:
        template = frappe.get_doc("Email Template", template_name)
        subject = render_string(template.subject, context) if hasattr(template, "subject") else ""
        body = render_string(template.response, context) if hasattr(template, "response") else ""
        return subject, body
    except Exception:
        logger.warning("Email Template '%s' not found", template_name)
        return "", ""


def _generate_unsubscribe_token(doctype: str, docname: str) -> str:
    """Generate a signed token for one-click unsubscribe links."""
    secret = frappe.conf.get("secret_key") or frappe.local.site
    payload = f"{doctype}:{docname}"
    return hashlib.sha256(f"{payload}:{secret}".encode()).hexdigest()[:32]


def _add_attachment_to_communication(comm_doc, fname: str, fcontent: bytes) -> None:
    """Attach a file to a Communication document via the File Manager."""
    try:
        from frappe.file_manager import save_file

        save_file(
            fname=fname,
            content=fcontent,
            dt="Communication",
            dn=comm_doc.name,
            is_private=1,
        )
    except Exception:
        logger.debug("Failed to attach file to Communication", exc_info=True)


def _get_pending_queue_items(
    max_retries: int,
    retry_interval: int,
) -> list[EmailQueue]:
    """Fetch pending queue items from the database."""
    try:
        rows = frappe.db.get_all(
            "Email Queue",
            filters={"status": ("in", ["Not Sent", "Error"])},
            fields=[
                "name",
                "sender",
                "recipients",
                "cc",
                "bcc",
                "subject",
                "message",
                "reference_doctype",
                "reference_name",
                "communication",
                "status",
                "retry",
                "read_receipt",
                "is_notification",
            ],
            order_by="creation asc",
            limit_page_length=100,
        )

        items: list[EmailQueue] = []
        for row in rows:
            if row.retry >= max_retries:
                continue

            # For error items, check retry interval
            if row.status == "Error" and row.retry > 0:
                # Skip if too soon to retry (simplified check)
                continue

            recipients = []
            try:
                recipients = json.loads(row.recipients) if row.recipients else []
            except json.JSONDecodeError:
                recipients = [r.strip() for r in row.recipients.split(",") if r.strip()]

            cc = []
            if row.cc:
                try:
                    cc = json.loads(row.cc)
                except json.JSONDecodeError:
                    cc = [r.strip() for r in row.cc.split(",") if r.strip()]

            bcc = []
            if row.bcc:
                try:
                    bcc = json.loads(row.bcc)
                except json.JSONDecodeError:
                    bcc = [r.strip() for r in row.bcc.split(",") if r.strip()]

            eq = EmailQueue(
                recipients=recipients,
                cc=cc,
                bcc=bcc,
                sender=row.sender,
                subject=row.subject,
                message=row.message,
                reference_doctype=row.reference_doctype,
                reference_name=row.reference_name,
                communication=row.communication,
                read_receipt=bool(row.read_receipt),
                is_notification=bool(row.is_notification),
            )
            eq.name = row.name
            eq.status = row.status
            eq.retry = row.retry
            items.append(eq)

        return items
    except Exception:
        logger.exception("Failed to fetch pending queue items")
        return []


def get_email_queue() -> list[dict]:
    """Return the current state of the email queue (for monitoring)."""
    try:
        return frappe.db.get_all(
            "Email Queue",
            fields=["name", "subject", "sender", "status", "retry", "creation"],
            order_by="creation desc",
            limit_page_length=200,
        )
    except Exception:
        return []
